// GENERATED FILE - DO NOT MODIFY BY HAND
// ignore_for_file: prefer_const_constructors

import 'package:currency_widget/currency_widget.dart';

final supportedCurrencies = <Currency>[
  Currency(
    code: "AED",
    name: "United Arab Emirates dirham",
    symbol: "د.إ",
    emoji: "🇦🇪",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "AFN",
    name: "Afghan afghani",
    symbol: "؋",
    emoji: "🇦🇫",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "ALL",
    name: "Albanian lek",
    symbol: "L",
    emoji: "🇦🇱",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "AMD",
    name: "Armenian dram",
    symbol: "֏",
    emoji: "🇦🇲",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "AOA",
    name: "Angolan kwanza",
    symbol: "Kz",
    emoji: "🇦🇴",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "ARS",
    name: "Argentine peso",
    symbol: "\$",
    emoji: "🇦🇷",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "AUD",
    name: "Australian dollar",
    symbol: "AU\$",
    emoji: "🇦🇺",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "AWG",
    name: "Aruban florin",
    symbol: "ƒ",
    emoji: "🇦🇼",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "AZN",
    name: "Azerbaijani manat",
    symbol: "₼",
    emoji: "🇦🇿",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "BAM",
    name: "Bosnia and Herzegovina convertible mark",
    symbol: "KM",
    emoji: "🇧🇦",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "BBD",
    name: "Barbados dollar",
    symbol: "Bds\$",
    emoji: "🇧🇧",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "BDT",
    name: "Bangladeshi taka",
    symbol: "৳",
    emoji: "🇧🇩",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "BGN",
    name: "Bulgarian lev",
    symbol: "лв",
    emoji: "🇧🇬",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "BHD",
    name: "Bahraini dinar",
    symbol: ".د.ب",
    emoji: "🇧🇭",
    decimal_digits: 3,
    position: "first",
  ),
  Currency(
    code: "BIF",
    name: "Burundian franc",
    symbol: "FBu",
    emoji: "🇧🇮",
    decimal_digits: 0,
    position: "last",
  ),
  Currency(
    code: "BMD",
    name: "Bermudian dollar",
    symbol: "BD\$",
    emoji: "🇧🇲",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "BND",
    name: "Brunei dollar",
    symbol: "B\$",
    emoji: "🇧🇳",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "BOB",
    name: "Boliviano",
    symbol: "Bs.",
    emoji: "🇧🇴",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "BOV",
    name: "Bolivian Mvdol (funds code)",
    symbol: "BOV",
    emoji: "🇧🇴",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "BRL",
    name: "Brazilian real",
    symbol: "R\$",
    emoji: "🇧🇷",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "BSD",
    name: "Bahamian dollar",
    symbol: "B\$",
    emoji: "🇧🇸",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "BTN",
    name: "Bhutanese ngultrum",
    symbol: "Nu.",
    emoji: "🇧🇹",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "BWP",
    name: "Botswana pula",
    symbol: "P",
    emoji: "🇧🇼",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "BYN",
    name: "Belarusian ruble",
    symbol: "Br",
    emoji: "🇧🇾",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "BZD",
    name: "Belize dollar",
    symbol: "BZ\$",
    emoji: "🇧🇿",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "CAD",
    name: "Canadian dollar",
    symbol: "CA\$",
    emoji: "🇨🇦",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "CDF",
    name: "Congolese franc",
    symbol: "FC",
    emoji: "🇨🇩",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "CHF",
    name: "Swiss franc",
    symbol: "CHF",
    emoji: "🇨🇭",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "CLF",
    name: "Unidad de Fomento (funds code)",
    symbol: "UF",
    emoji: "🇨🇱",
    decimal_digits: 4,
    position: "first",
  ),
  Currency(
    code: "CLP",
    name: "Chilean peso",
    symbol: "CLP\$",
    emoji: "🇨🇱",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "CNY",
    name: "Renminbi",
    symbol: "¥",
    emoji: "🇨🇳",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "COP",
    name: "Colombian peso",
    symbol: "COL\$",
    emoji: "🇨🇴",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "COU",
    name: "Unidad de Valor Real (UVR) (funds code)",
    symbol: "UVR",
    emoji: "🇨🇴",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "CRC",
    name: "Costa Rican colon",
    symbol: "₡",
    emoji: "🇨🇷",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "CUP",
    name: "Cuban peso",
    symbol: "₱",
    emoji: "🇨🇺",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "CVE",
    name: "Cape Verdean escudo",
    symbol: "Esc",
    emoji: "🇨🇻",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "CZK",
    name: "Czech koruna",
    symbol: "Kč",
    emoji: "🇨🇿",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "DJF",
    name: "Djiboutian franc",
    symbol: "Fdj",
    emoji: "🇩🇯",
    decimal_digits: 0,
    position: "last",
  ),
  Currency(
    code: "DKK",
    name: "Danish krone",
    symbol: "kr",
    emoji: "🇩🇰",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "DOP",
    name: "Dominican peso",
    symbol: "RD\$",
    emoji: "🇩🇴",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "DZD",
    name: "Algerian dinar",
    symbol: "دج",
    emoji: "🇩🇿",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "EGP",
    name: "Egyptian pound",
    symbol: "£",
    emoji: "🇪🇬",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "ERN",
    name: "Eritrean nakfa",
    symbol: "Nfk",
    emoji: "🇪🇷",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "ETB",
    name: "Ethiopian birr",
    symbol: "Br",
    emoji: "🇪🇹",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "EUR",
    name: "Euro",
    symbol: "€",
    emoji: "🇪🇺",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "FJD",
    name: "Fiji dollar",
    symbol: "FJ\$",
    emoji: "🇫🇯",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "FKP",
    name: "Falkland Islands pound",
    symbol: "£",
    emoji: "🇫🇰",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "GBP",
    name: "Pound sterling",
    symbol: "£",
    emoji: "🇬🇧",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "GEL",
    name: "Georgian lari",
    symbol: "₾",
    emoji: "🇬🇪",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "GHS",
    name: "Ghanaian cedi",
    symbol: "₵",
    emoji: "🇬🇭",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "GIP",
    name: "Gibraltar pound",
    symbol: "£",
    emoji: "🇬🇮",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "GMD",
    name: "Gambian dalasi",
    symbol: "D",
    emoji: "🇬🇲",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "GNF",
    name: "Guinean franc",
    symbol: "FG",
    emoji: "🇬🇳",
    decimal_digits: 0,
    position: "last",
  ),
  Currency(
    code: "GTQ",
    name: "Guatemalan quetzal",
    symbol: "Q",
    emoji: "🇬🇹",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "GYD",
    name: "Guyanese dollar",
    symbol: "GY\$",
    emoji: "🇬🇾",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "HKD",
    name: "Hong Kong dollar",
    symbol: "HK\$",
    emoji: "🇭🇰",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "HNL",
    name: "Honduran lempira",
    symbol: "L",
    emoji: "🇭🇳",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "HTG",
    name: "Haitian gourde",
    symbol: "G",
    emoji: "🇭🇹",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "HUF",
    name: "Hungarian forint",
    symbol: "Ft",
    emoji: "🇭🇺",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "IDR",
    name: "Indonesian rupiah",
    symbol: "Rp",
    emoji: "🇮🇩",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "ILS",
    name: "Israeli new shekel",
    symbol: "₪",
    emoji: "🇮🇱",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "INR",
    name: "Indian rupee",
    symbol: "₹",
    emoji: "🇮🇳",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "IQD",
    name: "Iraqi dinar",
    symbol: "ع.د",
    emoji: "🇮🇶",
    decimal_digits: 3,
    position: "first",
  ),
  Currency(
    code: "IRR",
    name: "Iranian rial",
    symbol: "﷼",
    emoji: "🇮🇷",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "ISK",
    name: "Icelandic króna",
    symbol: "kr",
    emoji: "🇮🇸",
    decimal_digits: 0,
    position: "last",
  ),
  Currency(
    code: "JMD",
    name: "Jamaican dollar",
    symbol: "J\$",
    emoji: "🇯🇲",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "JOD",
    name: "Jordanian dinar",
    symbol: "JD",
    emoji: "🇯🇴",
    decimal_digits: 3,
    position: "first",
  ),
  Currency(
    code: "JPY",
    name: "Japanese yen",
    symbol: "¥",
    emoji: "🇯🇵",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "KES",
    name: "Kenyan shilling",
    symbol: "KSh",
    emoji: "🇰🇪",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "KGS",
    name: "Kyrgyzstani som",
    symbol: "лв",
    emoji: "🇰🇬",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "KHR",
    name: "Cambodian riel",
    symbol: "៛",
    emoji: "🇰🇭",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "KMF",
    name: "Comoro franc",
    symbol: "CF",
    emoji: "🇰🇲",
    decimal_digits: 0,
    position: "last",
  ),
  Currency(
    code: "KPW",
    name: "North Korean won",
    symbol: "₩",
    emoji: "🇰🇵",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "KRW",
    name: "South Korean won",
    symbol: "₩",
    emoji: "🇰🇷",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "KWD",
    name: "Kuwaiti dinar",
    symbol: "د.ك",
    emoji: "🇰🇼",
    decimal_digits: 3,
    position: "first",
  ),
  Currency(
    code: "KYD",
    name: "Cayman Islands dollar",
    symbol: "CI\$",
    emoji: "🇰🇾",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "KZT",
    name: "Kazakhstani tenge",
    symbol: "₸",
    emoji: "🇰🇿",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "LAK",
    name: "Lao kip",
    symbol: "₭",
    emoji: "🇱🇦",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "LBP",
    name: "Lebanese pound",
    symbol: "£",
    emoji: "🇱🇧",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "LKR",
    name: "Sri Lankan rupee",
    symbol: "Rs",
    emoji: "🇱🇰",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "LRD",
    name: "Liberian dollar",
    symbol: "L\$",
    emoji: "🇱🇷",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "LSL",
    name: "Lesotho loti",
    symbol: "M",
    emoji: "🇱🇸",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "LYD",
    name: "Libyan dinar",
    symbol: "ل.د",
    emoji: "🇱🇾",
    decimal_digits: 3,
    position: "first",
  ),
  Currency(
    code: "MAD",
    name: "Moroccan dirham",
    symbol: "د.م.",
    emoji: "🇲🇦",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "MDL",
    name: "Moldovan leu",
    symbol: "L",
    emoji: "🇲🇩",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "MGA",
    name: "Malagasy ariary",
    symbol: "Ar",
    emoji: "🇲🇬",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "MKD",
    name: "Macedonian denar",
    symbol: "ден",
    emoji: "🇲🇰",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "MMK",
    name: "Myanmar kyat",
    symbol: "K",
    emoji: "🇲🇲",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "MNT",
    name: "Mongolian tögrög",
    symbol: "₮",
    emoji: "🇲🇳",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "MOP",
    name: "Macanese pataca",
    symbol: "P",
    emoji: "🇲🇴",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "MRU",
    name: "Mauritanian ouguiya",
    symbol: "UM",
    emoji: "🇲🇷",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "MUR",
    name: "Mauritian rupee",
    symbol: "Rs",
    emoji: "🇲🇺",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "MVR",
    name: "Maldivian rufiyaa",
    symbol: "Rf",
    emoji: "🇲🇻",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "MWK",
    name: "Malawian kwacha",
    symbol: "MK",
    emoji: "🇲🇼",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "MXN",
    name: "Mexican peso",
    symbol: "\$",
    emoji: "🇲🇽",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "MXV",
    name: "Mexican Unidad de Inversion (UDI) (funds code)",
    symbol: "MXV",
    emoji: "🇲🇽",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "MYR",
    name: "Malaysian ringgit",
    symbol: "RM",
    emoji: "🇲🇾",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "MZN",
    name: "Mozambican metical",
    symbol: "MT",
    emoji: "🇲🇿",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "NAD",
    name: "Namibian dollar",
    symbol: "N\$",
    emoji: "🇳🇦",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "NGN",
    name: "Nigerian naira",
    symbol: "₦",
    emoji: "🇳🇬",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "NIO",
    name: "Nicaraguan córdoba",
    symbol: "C\$",
    emoji: "🇳🇮",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "NOK",
    name: "Norwegian krone",
    symbol: "kr",
    emoji: "🇳🇴",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "NPR",
    name: "Nepalese rupee",
    symbol: "Rs",
    emoji: "🇳🇵",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "NZD",
    name: "New Zealand dollar",
    symbol: "NZ\$",
    emoji: "🇳🇿",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "OMR",
    name: "Omani rial",
    symbol: "ر.ع.",
    emoji: "🇴🇲",
    decimal_digits: 3,
    position: "first",
  ),
  Currency(
    code: "PAB",
    name: "Panamanian balboa",
    symbol: "B/.",
    emoji: "🇵🇦",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "PEN",
    name: "Peruvian sol",
    symbol: "S/",
    emoji: "🇵🇪",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "PGK",
    name: "Papua New Guinean kina",
    symbol: "K",
    emoji: "🇵🇬",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "PHP",
    name: "Philippine peso",
    symbol: "₱",
    emoji: "🇵🇭",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "PKR",
    name: "Pakistani rupee",
    symbol: "Rs",
    emoji: "🇵🇰",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "PLN",
    name: "Polish złoty",
    symbol: "zł",
    emoji: "🇵🇱",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "PYG",
    name: "Paraguayan guaraní",
    symbol: "₲",
    emoji: "🇵🇾",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "QAR",
    name: "Qatari riyal",
    symbol: "ر.ق",
    emoji: "🇶🇦",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "RON",
    name: "Romanian leu",
    symbol: "lei",
    emoji: "🇷🇴",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "RSD",
    name: "Serbian dinar",
    symbol: "дин.",
    emoji: "🇷🇸",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "RUB",
    name: "Russian ruble",
    symbol: "₽",
    emoji: "🇷🇺",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "RWF",
    name: "Rwandan franc",
    symbol: "FRw",
    emoji: "🇷🇼",
    decimal_digits: 0,
    position: "last",
  ),
  Currency(
    code: "SAR",
    name: "Saudi riyal",
    symbol: "ر.س",
    emoji: "🇸🇦",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "SBD",
    name: "Solomon Islands dollar",
    symbol: "SI\$",
    emoji: "🇸🇧",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "SCR",
    name: "Seychelles rupee",
    symbol: "SR",
    emoji: "🇸🇨",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "SDG",
    name: "Sudanese pound",
    symbol: "SDG",
    emoji: "🇸🇩",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "SEK",
    name: "Swedish krona",
    symbol: "kr",
    emoji: "🇸🇪",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "SGD",
    name: "Singapore dollar",
    symbol: "S\$",
    emoji: "🇸🇬",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "SHP",
    name: "Saint Helena pound",
    symbol: "£",
    emoji: "🇸🇭",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "SLE",
    name: "Sierra Leonean leone",
    symbol: "Le",
    emoji: "🇸🇱",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "SOS",
    name: "Somalian shilling",
    symbol: "Ssh",
    emoji: "🇸🇴",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "SRD",
    name: "Surinamese dollar",
    symbol: "SR\$",
    emoji: "🇸🇷",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "SSP",
    name: "South Sudanese pound",
    symbol: "SS£",
    emoji: "🇸🇸",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "STN",
    name: "São Tomé and Príncipe dobra",
    symbol: "Db",
    emoji: "🇸🇹",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "SVC",
    name: "Salvadoran colón",
    symbol: "₡",
    emoji: "🇸🇻",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "SYP",
    name: "Syrian pound",
    symbol: "£",
    emoji: "🇸🇾",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "SZL",
    name: "Swazi lilangeni",
    symbol: "E",
    emoji: "🇸🇿",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "THB",
    name: "Thai baht",
    symbol: "฿",
    emoji: "🇹🇭",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "TJS",
    name: "Tajikistani somoni",
    symbol: "ЅМ",
    emoji: "🇹🇯",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "TMT",
    name: "Turkmenistan manat",
    symbol: "m",
    emoji: "🇹🇲",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "TND",
    name: "Tunisian dinar",
    symbol: "د.ت",
    emoji: "🇹🇳",
    decimal_digits: 3,
    position: "first",
  ),
  Currency(
    code: "TOP",
    name: "Tongan paʻanga",
    symbol: "T\$",
    emoji: "🇹🇴",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "TRY",
    name: "Turkish lira",
    symbol: "₺",
    emoji: "🇹🇷",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "TTD",
    name: "Trinidad and Tobago dollar",
    symbol: "TT\$",
    emoji: "🇹🇹",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "TWD",
    name: "New Taiwan dollar",
    symbol: "NT\$",
    emoji: "🇹🇼",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "TZS",
    name: "Tanzanian shilling",
    symbol: "TZS",
    emoji: "🇹🇿",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "UAH",
    name: "Ukrainian hryvnia",
    symbol: "₴",
    emoji: "🇺🇦",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "UGX",
    name: "Ugandan shilling",
    symbol: "USh",
    emoji: "🇺🇬",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "USD",
    name: "United States dollar",
    symbol: "\$",
    emoji: "🇺🇸",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "USN",
    name: "United States dollar (next day)",
    symbol: "USN",
    emoji: "🇺🇸",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "UYI",
    name: "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)",
    symbol: "UYI",
    emoji: "🇺🇾",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "UYU",
    name: "Uruguayan peso",
    symbol: "\$U",
    emoji: "🇺🇾",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "UYW",
    name: "Unidad previsional",
    symbol: "UYW",
    emoji: "🇺🇾",
    decimal_digits: 4,
    position: "first",
  ),
  Currency(
    code: "UZS",
    name: "Uzbekistani soʻm",
    symbol: "лв",
    emoji: "🇺🇿",
    decimal_digits: 2,
    position: "last",
  ),
  Currency(
    code: "VES",
    name: "Venezuelan bolívar soberano",
    symbol: "Bs.",
    emoji: "🇻🇪",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "VND",
    name: "Vietnamese đồng",
    symbol: "₫",
    emoji: "🇻🇳",
    decimal_digits: 0,
    position: "last",
  ),
  Currency(
    code: "VUV",
    name: "Vanuatu vatu",
    symbol: "VT",
    emoji: "🇻🇺",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "WST",
    name: "Samoan tala",
    symbol: "WS\$",
    emoji: "🇼🇸",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "XAF",
    name: "Central African CFA franc",
    symbol: "FCFA",
    emoji: "🇨🇲",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XAG",
    name: "Silver (one troy ounce)",
    symbol: "XAG",
    emoji: "🪙",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XAU",
    name: "Gold (one troy ounce)",
    symbol: "XAU",
    emoji: "🪙",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XBA",
    name: "European Composite Unit (EURCO) (bond market unit)",
    symbol: "XBA",
    emoji: "🇪🇺",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XBB",
    name: "European Monetary Unit (E.M.U.-6) (bond market unit)",
    symbol: "XBB",
    emoji: "🇪🇺",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XBC",
    name: "European Unit of Account 9 (E.U.A.-9) (bond market unit)",
    symbol: "XBC",
    emoji: "🇪🇺",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XBD",
    name: "European Unit of Account 17 (E.U.A.-17) (bond market unit)",
    symbol: "XBD",
    emoji: "🇪🇺",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XCD",
    name: "East Caribbean dollar",
    symbol: "EC\$",
    emoji: "🇰🇳",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "XDR",
    name: "Special Drawing Rights",
    symbol: "SDR",
    emoji: "🏦",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XOF",
    name: "West African CFA franc",
    symbol: "CFA",
    emoji: "🇨🇮",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XPD",
    name: "Palladium (one troy ounce)",
    symbol: "XPD",
    emoji: "🪙",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XPF",
    name: "CFP franc",
    symbol: "F",
    emoji: "🇵🇫",
    decimal_digits: 0,
    position: "last",
  ),
  Currency(
    code: "XPT",
    name: "Platinum (one troy ounce)",
    symbol: "XPT",
    emoji: "🪙",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XSU",
    name: "Sucre",
    symbol: "XSU",
    emoji: "🇪🇨",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XTS",
    name: "Codes specifically reserved for testing purposes",
    symbol: "XTS",
    emoji: "❓",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XUA",
    name: "ADB Unit of Account",
    symbol: "XUA",
    emoji: "🏦",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "XXX",
    name: "The codes assigned for transactions where no currency is involved",
    symbol: "XXX",
    emoji: "❌",
    decimal_digits: 0,
    position: "first",
  ),
  Currency(
    code: "YER",
    name: "Yemeni rial",
    symbol: "﷼",
    emoji: "🇾🇪",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "ZAR",
    name: "South African rand",
    symbol: "R",
    emoji: "🇿🇦",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "ZMW",
    name: "Zambian kwacha",
    symbol: "ZK",
    emoji: "🇿🇲",
    decimal_digits: 2,
    position: "first",
  ),
  Currency(
    code: "ZWL",
    name: "Zimbabwean dollar",
    symbol: "Z\$",
    emoji: "🇿🇼",
    decimal_digits: 2,
    position: "first",
  ),
];
